export { LOCALES, THEMES, type Locale, type Theme } from './model/types'
export { resolveTheme } from './model/resolve-theme'
export { createSettingsStore, SETTINGS_STORAGE_KEY, type SettingsStore } from './model/store'
export { selectLocale, selectTheme } from './model/selectors'
export { SettingsStoreProvider, useSettings, useSettingsStoreApi } from './model/context'
