export type { FigureChange, FigureChoice, SetupChange, SetupParams } from './model/setup-params'
export { ChordSizeField } from './ui/ChordSizeField'
export { FigureRows } from './ui/FigureRows'
export { MelodySwitch } from './ui/MelodySwitch'
export { PlayerSetup } from './ui/PlayerSetup'
