import { SCALE_KINDS } from '@/shared/lib/music'
import { OCTAVES } from '../model/choice'
import type { Exercise } from '../model/types'

const FEW_OCTAVES = [1, 2] as const
const BARRY_HARRIS = 'Barry Harris'
const JONNY = 'Piano With Jonny'

/**
 * Practice's exercises, by group in the page's order (roadmap §10.5, spec §3): each written for the
 * app from its method's idea; Hanon's No. 1 is public domain.
 */
export const EXERCISES: readonly Exercise[] = [
  {
    id: 'scale',
    group: 'scales',
    level: 1,
    name: { en: 'Scale', ru: 'Гамма' },
    trains: {
      en: 'Any scale up and down, from any of its notes, over one to four octaves',
      ru: 'Любая гамма вверх и вниз, от любой её ноты, на одну–четыре октавы',
    },
    fields: { root: 'scale', kind: SCALE_KINDS, octaves: OCTAVES, start: true, fingering: true },
    own: { kind: 'major', octaves: 2 },
    tempo: 80,
    swing: false,
  },
  {
    id: 'thirds',
    group: 'scales',
    level: 2,
    name: { en: 'In 3rds', ru: 'Терциями' },
    trains: {
      en: 'The scale in broken 3rds: each note and the one a 3rd above',
      ru: 'Гамма ломаными терциями: каждая нота и нота терцией выше',
    },
    fields: { root: 'scale', kind: SCALE_KINDS, octaves: FEW_OCTAVES },
    own: { kind: 'major', octaves: 1 },
    tempo: 72,
    swing: false,
  },
  {
    id: 'sixths',
    group: 'scales',
    level: 3,
    name: { en: 'In 6ths', ru: 'Секстами' },
    trains: {
      en: 'The scale in broken 6ths: a wider reach, the same way up and back',
      ru: 'Гамма ломаными секстами: шире растяжка, тот же путь вверх и назад',
    },
    fields: { root: 'scale', kind: SCALE_KINDS, octaves: FEW_OCTAVES },
    own: { kind: 'major', octaves: 1 },
    tempo: 66,
    swing: false,
  },
  {
    id: 'groups',
    group: 'scales',
    level: 2,
    name: { en: 'In groups', ru: 'Группами' },
    trains: {
      en: 'A group of four notes restarted on each degree, up and mirrored down',
      ru: 'Группа из четырёх нот от каждой ступени, вверх и зеркально вниз',
    },
    fields: { root: 'scale', kind: SCALE_KINDS, octaves: FEW_OCTAVES, figure: ['1234', '1324'] },
    own: { kind: 'major', octaves: 1, figure: '1234' },
    tempo: 72,
    swing: false,
  },
  {
    id: 'contrary',
    group: 'scales',
    level: 2,
    name: { en: 'Contrary motion', ru: 'Расходящееся движение' },
    trains: {
      en: 'Both hands from one note, moving apart and back together',
      ru: 'Обе руки от одной ноты расходятся и сходятся обратно',
    },
    fields: { root: 'scale', kind: SCALE_KINDS, octaves: FEW_OCTAVES },
    own: { kind: 'major', octaves: 1 },
    tempo: 72,
    swing: false,
  },
  {
    id: 'arpeggio',
    group: 'arpeggios',
    level: 2,
    name: { en: 'Arpeggio', ru: 'Арпеджио' },
    trains: {
      en: 'A chord’s notes one by one over the octaves, from any inversion',
      ru: 'Звуки аккорда по одному через октавы, от любого обращения',
    },
    fields: { root: 'chord', quality: true, inversion: [0, 1, 2, 3], octaves: OCTAVES },
    own: { quality: 'maj', inversion: 0, octaves: 2 },
    tempo: 72,
    swing: false,
  },
  {
    id: 'chords-of-scale',
    group: 'chords',
    level: 2,
    name: { en: 'Chords of a scale', ru: 'Аккорды гаммы' },
    trains: {
      en: 'A scale’s chords up and down, in any size, inversion and pattern',
      ru: 'Аккорды гаммы вверх и вниз, любого размера, обращения и фактуры',
    },
    opens: { player: 'walk' },
  },
  {
    id: 'chords-by-semitones',
    group: 'chords',
    level: 2,
    name: { en: 'Chords by semitones', ru: 'Аккорды по полутонам' },
    trains: {
      en: 'Chosen chords root by root, a semitone at a time',
      ru: 'Выбранные аккорды от каждого звука, по полутону',
    },
    opens: { player: 'chromatic' },
  },
  {
    id: 'sixth-diminished',
    group: 'barryHarris',
    level: 3,
    name: { en: '6th-diminished scale', ru: 'Секстово-уменьшённая гамма' },
    trains: {
      en: 'Eight notes an octave: the 6th chord on the beats, the diminished 7th between',
      ru: 'Восемь нот в октаве: секстаккорд на долях, уменьшённый септаккорд между ними',
    },
    source: BARRY_HARRIS,
    fields: { root: 'key', tonality: true, octaves: FEW_OCTAVES },
    own: { tonality: 'major', octaves: 1 },
    tempo: 80,
    swing: true,
  },
  {
    id: 'sixth-diminished-chords',
    group: 'barryHarris',
    level: 4,
    name: { en: '6th-diminished chords', ru: 'Секстово-уменьшённые аккорды' },
    trains: {
      en: 'Each note of the 6th-diminished scale harmonised, close or in drop 2',
      ru: 'Каждая нота секстово-уменьшённой гаммы с аккордом, тесно или drop 2',
    },
    source: BARRY_HARRIS,
    fields: { root: 'key', tonality: true, voicing: true },
    own: { tonality: 'major', voicing: 'close' },
    tempo: 66,
    swing: false,
  },
  {
    id: 'dominant-scale',
    group: 'barryHarris',
    level: 3,
    name: { en: 'Dominant scale down', ru: 'Доминантовая гамма вниз' },
    trains: {
      en: 'The V7’s scale down with a half step that puts its chord tones on the beats',
      ru: 'Гамма V7 вниз с полутоном, который ставит звуки аккорда на доли',
    },
    source: BARRY_HARRIS,
    fields: { root: 'key', from: true },
    own: { from: 'root' },
    tempo: 92,
    swing: true,
  },
  {
    id: 'from-third',
    group: 'barryHarris',
    level: 4,
    name: { en: 'Arpeggios from the 3rd', ru: 'Арпеджио от терции' },
    trains: {
      en: 'Over a ii–V–I: each chord’s 3-5-7-9, then the scale down into the next',
      ru: 'В обороте ii–V–I: 3-5-7-9 каждого аккорда, затем гамма вниз к следующему',
    },
    source: BARRY_HARRIS,
    fields: { root: 'key' },
    own: {},
    tempo: 84,
    swing: true,
  },
  {
    id: 'drop-two',
    group: 'barryHarris',
    level: 4,
    name: { en: 'Drop-2 7ths', ru: '7-е аккорды drop 2' },
    trains: {
      en: 'The key’s 7th chords up and down, the second voice from the top in the left hand',
      ru: 'Септаккорды тональности вверх и вниз, второй сверху голос в левой руке',
    },
    source: BARRY_HARRIS,
    fields: { root: 'key', inversion: [0, 1, 2, 3] },
    own: { inversion: 0 },
    tempo: 60,
    swing: false,
  },
  {
    id: 'two-five-one-scale',
    group: 'jonny',
    level: 1,
    name: { en: '2-5-1 scale', ru: 'Гамма 2-5-1' },
    trains: {
      en: 'The scale in swung 8ths over the left hand’s shells of a ii–V–I',
      ru: 'Гамма свингующими восьмыми над «скелетами» ii–V–I в левой руке',
    },
    source: JONNY,
    fields: { root: 'key' },
    own: {},
    tempo: 96,
    swing: true,
  },
  {
    id: 'inner-voice',
    group: 'jonny',
    level: 2,
    name: { en: 'Inner voice', ru: 'Внутренний голос' },
    trains: {
      en: 'The key’s 7th chords: the 3rd held on top, the 7th stepping down to the 6th',
      ru: 'Септаккорды тональности: терция держится сверху, септима спускается к сексте',
    },
    source: JONNY,
    fields: { root: 'key' },
    own: {},
    tempo: 66,
    swing: false,
  },
  {
    id: 'modes',
    group: 'jonny',
    level: 3,
    name: { en: 'Modes', ru: 'Лады' },
    trains: {
      en: 'The scale from each of its degrees, Ionian to Locrian, fingered as the scale',
      ru: 'Гамма от каждой ступени, от ионийского до локрийского, с аппликатурой гаммы',
    },
    source: JONNY,
    fields: { root: 'key' },
    own: {},
    tempo: 80,
    swing: false,
  },
  {
    id: 'rapid-switch',
    group: 'jonny',
    level: 4,
    name: { en: 'Rapid switch', ru: 'Быстрая смена' },
    trains: {
      en: 'One unbroken line through all twelve keys round the circle of fifths',
      ru: 'Одна непрерывная линия через все двенадцать тональностей по квинтовому кругу',
    },
    source: JONNY,
    fields: { root: 'key' },
    own: {},
    tempo: 84,
    swing: false,
  },
  {
    id: 'pattern-shifting',
    group: 'jonny',
    level: 4,
    name: { en: 'Pattern shifting', ru: 'Перенос фигуры' },
    trains: {
      en: 'A short figure restarted on each degree, its shape kept: a melodic sequence',
      ru: 'Короткая фигура от каждой ступени с той же формой: мелодическая секвенция',
    },
    source: JONNY,
    fields: { root: 'key', figure: ['1235', '1353', '3212'] },
    own: { figure: '1235' },
    tempo: 84,
    swing: true,
  },
  {
    id: 'two-five-one-keys',
    group: 'progressions',
    level: 2,
    name: { en: 'ii–V–I through the keys', ru: 'ii–V–I по тональностям' },
    trains: {
      en: 'The jazz cadence in every key, round the circle',
      ru: 'Джазовый оборот во всех тональностях, по кругу',
    },
    opens: { player: 'progression', numerals: 'ii7 V7 IMaj7', walk: 'fifths' },
  },
  {
    id: 'turnaround-keys',
    group: 'progressions',
    level: 3,
    name: { en: 'I–vi–ii–V through the keys', ru: 'I–vi–ii–V по тональностям' },
    trains: {
      en: 'The turnaround in every key, round the circle',
      ru: 'Оборот I–vi–ii–V во всех тональностях, по кругу',
    },
    opens: { player: 'progression', numerals: 'IMaj7 vi7 ii7 V7', walk: 'fifths' },
  },
  {
    id: 'circle-keys',
    group: 'progressions',
    level: 3,
    name: { en: 'Round the circle through the keys', ru: 'Квинтовый круг по тональностям' },
    trains: {
      en: 'Every degree of the key a 5th apart, home to I, in every key',
      ru: 'Все ступени тональности через квинту и домой к I, во всех тональностях',
    },
    opens: { player: 'progression', numerals: 'I IV vii° iii vi ii V I', walk: 'fifths' },
  },
  {
    id: 'five-finger',
    group: 'technique',
    level: 1,
    name: { en: 'Five-finger position', ru: 'Позиция пяти пальцев' },
    trains: {
      en: 'A finger on each of the first five notes of a key, up and down',
      ru: 'Палец на каждой из пяти первых нот тональности, вверх и вниз',
    },
    fields: { root: 'key', tonality: true },
    own: { tonality: 'major' },
    tempo: 80,
    swing: false,
  },
  {
    id: 'hanon',
    group: 'technique',
    level: 2,
    name: { en: 'Hanon No. 1', ru: 'Ганон № 1' },
    trains: {
      en: 'An even, independent hand: one figure climbing two octaves and coming back',
      ru: 'Ровность и независимость пальцев: одна фигура на две октавы вверх и обратно',
    },
    source: 'C.-L. Hanon',
    fields: { root: 'key' },
    own: {},
    tempo: 92,
    swing: false,
  },
]
