export { setAutoNext } from './set-auto-next'
export { setKeyboard } from './set-keyboard'
export { setLocale } from './set-locale'
export { setPracticeToggle } from './set-practice-toggle'
export { setTheme } from './set-theme'
