export { checkPlan, isTrainerId } from '@/features/trainer'
export { CheckPage } from '@/pages/check'
export { ExercisesPage } from '@/pages/exercises'
export { FreePlayPage } from '@/pages/free-play'
export { PracticePage } from '@/pages/practice'
export { QuizPage } from '@/pages/quiz'
export { TrainerPage } from '@/pages/trainer'
